CREATE TABLE IF NOT EXISTS app_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phone VARCHAR(20) NOT NULL UNIQUE,
    student_id VARCHAR(32) UNIQUE,
    real_name VARCHAR(50),
    nickname VARCHAR(50) NOT NULL,
    avatar_url VARCHAR(500),
    password_hash VARCHAR(100) NOT NULL,
    contact_phone VARCHAR(20),
    role VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    last_login_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    deleted_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS user_auth (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    auth_type VARCHAR(20) NOT NULL,
    auth_status VARCHAR(20) NOT NULL,
    identifier VARCHAR(100) NOT NULL,
    verified_at TIMESTAMP WITH TIME ZONE,
    reject_reason VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_test_user_auth_user FOREIGN KEY (user_id) REFERENCES app_user(id),
    CONSTRAINT uk_test_user_auth_identity UNIQUE (user_id, auth_type, identifier)
);

CREATE TABLE IF NOT EXISTS user_address (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    contact_name VARCHAR(50) NOT NULL,
    contact_phone VARCHAR(20) NOT NULL,
    campus VARCHAR(100) NOT NULL,
    building VARCHAR(100) NOT NULL,
    room VARCHAR(100),
    detail VARCHAR(255),
    is_default BOOLEAN NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    deleted_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_test_user_address_user FOREIGN KEY (user_id) REFERENCES app_user(id)
);

CREATE TABLE IF NOT EXISTS category (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id BIGINT,
    name VARCHAR(50) NOT NULL,
    icon VARCHAR(255),
    sort_order INTEGER NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_test_category_parent FOREIGN KEY (parent_id) REFERENCES category(id)
);

CREATE TABLE IF NOT EXISTS product (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    seller_id BIGINT NOT NULL,
    category_id BIGINT NOT NULL,
    title VARCHAR(80) NOT NULL,
    description CLOB NOT NULL,
    price NUMERIC(10,2) NOT NULL,
    original_price NUMERIC(10,2),
    condition_level VARCHAR(20) NOT NULL,
    trade_type VARCHAR(20) NOT NULL,
    trade_location VARCHAR(255),
    status VARCHAR(30) NOT NULL,
    view_count INTEGER NOT NULL,
    favorite_count INTEGER NOT NULL,
    published_at TIMESTAMP WITH TIME ZONE,
    sold_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    deleted_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_test_product_seller FOREIGN KEY (seller_id) REFERENCES app_user(id),
    CONSTRAINT fk_test_product_category FOREIGN KEY (category_id) REFERENCES category(id)
);

CREATE TABLE IF NOT EXISTS product_image (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL,
    image_url VARCHAR(500) NOT NULL,
    sort_order INTEGER NOT NULL,
    is_main BOOLEAN NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_test_product_image_product FOREIGN KEY (product_id) REFERENCES product(id) ON DELETE CASCADE,
    CONSTRAINT uk_test_product_image_sort UNIQUE (product_id, sort_order)
);

CREATE TABLE IF NOT EXISTS favorite (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_test_favorite_user FOREIGN KEY (user_id) REFERENCES app_user(id),
    CONSTRAINT fk_test_favorite_product FOREIGN KEY (product_id) REFERENCES product(id) ON DELETE CASCADE,
    CONSTRAINT uk_test_favorite_user_product UNIQUE (user_id, product_id)
);

CREATE TABLE IF NOT EXISTS trade_order (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_no VARCHAR(32) NOT NULL UNIQUE,
    buyer_id BIGINT NOT NULL,
    seller_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    address_id BIGINT,
    price NUMERIC(10,2) NOT NULL,
    trade_type VARCHAR(20) NOT NULL,
    buyer_remark VARCHAR(200),
    pickup_time TIMESTAMP WITH TIME ZONE,
    pickup_location VARCHAR(255),
    status VARCHAR(30) NOT NULL,
    cancel_reason VARCHAR(255),
    cancelled_by BIGINT,
    confirmed_at TIMESTAMP WITH TIME ZONE,
    completed_at TIMESTAMP WITH TIME ZONE,
    cancelled_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_test_order_buyer FOREIGN KEY (buyer_id) REFERENCES app_user(id),
    CONSTRAINT fk_test_order_seller FOREIGN KEY (seller_id) REFERENCES app_user(id),
    CONSTRAINT fk_test_order_product FOREIGN KEY (product_id) REFERENCES product(id),
    CONSTRAINT fk_test_order_address FOREIGN KEY (address_id) REFERENCES user_address(id),
    CONSTRAINT fk_test_order_cancelled_by FOREIGN KEY (cancelled_by) REFERENCES app_user(id)
);

CREATE TABLE IF NOT EXISTS conversation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL,
    buyer_id BIGINT NOT NULL,
    seller_id BIGINT NOT NULL,
    last_message VARCHAR(500),
    last_message_at TIMESTAMP WITH TIME ZONE,
    buyer_unread_count INTEGER NOT NULL DEFAULT 0,
    seller_unread_count INTEGER NOT NULL DEFAULT 0,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_test_conversation_product FOREIGN KEY (product_id) REFERENCES product(id),
    CONSTRAINT fk_test_conversation_buyer FOREIGN KEY (buyer_id) REFERENCES app_user(id),
    CONSTRAINT fk_test_conversation_seller FOREIGN KEY (seller_id) REFERENCES app_user(id),
    CONSTRAINT uk_test_conversation_unique UNIQUE (product_id, buyer_id, seller_id)
);

CREATE TABLE IF NOT EXISTS message (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id BIGINT NOT NULL,
    sender_id BIGINT NOT NULL,
    content CLOB NOT NULL,
    message_type VARCHAR(20) NOT NULL DEFAULT 'TEXT',
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    read_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_test_message_conversation FOREIGN KEY (conversation_id) REFERENCES conversation(id) ON DELETE CASCADE,
    CONSTRAINT fk_test_message_sender FOREIGN KEY (sender_id) REFERENCES app_user(id)
);

CREATE TABLE IF NOT EXISTS blacklist (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    reason VARCHAR(255) NOT NULL,
    operator_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    removed_reason VARCHAR(255),
    removed_by BIGINT,
    removed_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_test_blacklist_user FOREIGN KEY (user_id) REFERENCES app_user(id),
    CONSTRAINT fk_test_blacklist_operator FOREIGN KEY (operator_id) REFERENCES app_user(id),
    CONSTRAINT fk_test_blacklist_removed_by FOREIGN KEY (removed_by) REFERENCES app_user(id)
);

CREATE TABLE IF NOT EXISTS audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL,
    operator_id BIGINT NOT NULL,
    action VARCHAR(30) NOT NULL,
    from_status VARCHAR(30),
    to_status VARCHAR(30) NOT NULL,
    reason VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_test_audit_product FOREIGN KEY (product_id) REFERENCES product(id),
    CONSTRAINT fk_test_audit_operator FOREIGN KEY (operator_id) REFERENCES app_user(id)
);

MERGE INTO category (id, parent_id, name, icon, sort_order, status, created_at, updated_at) KEY(id) VALUES
    (1, NULL, '教材', 'book', 10, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (2, NULL, '数码', 'device', 20, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (3, NULL, '宿舍用品', 'home', 30, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (4, NULL, '运动器材', 'sport', 40, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (5, NULL, '其他', 'more', 99, 'ACTIVE', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
